import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import About from '../components/About'
import WhatWeDo from '../components/WhatWeDo'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fagus NS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <About />
      <WhatWeDo />
    </div>
  )
}

export default Home
